security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    role_hierarchy:
        ROLE_USER: ROLE_USER
        ROLE_COVID19_VIEWER: ROLE_COVID19_VIEWER, ROLE_USER
        ROLE_PARTNER: ROLE_COVID19_VIEWER
        ROLE_NORMAL_USER: ROLE_PARTNER, ROLE_USER
        ROLE_COVID19_EDITOR: ROLE_COVID19_VIEWER
        ROLE_RESTRICTED_EDITOR: ROLE_PARTNER
        ROLE_EDITOR: [ROLE_COVID19_EDITOR, ROLE_RESTRICTED_EDITOR, ROLE_NORMAL_USER]
        ROLE_ADMIN: ROLE_EDITOR
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        api:
            pattern: ^/api/
            anonymous: true
            stateless: true
            guard:
                authenticators:
                    - 'jwt_token_authenticator'
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        #main:
        main:
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 2592000  # 1 month in seconds
                path: /
                # by default, the feature is enabled by checking a
                # checkbox in the login form (see below), uncomment the
                # following line to always enable it.
                always_remember_me: true
            pattern: ^/
            anonymous: lazy
            provider: app_user_provider
            guard:
                #entry_point: App\Security\AppFormAuthenticator
                authenticators:
                    - App\Security\AppFormAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route


            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
        - { path: '^/login', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/auth/token', roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: '^/api_test', roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: '^/reset-password/.*', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/user/.*', roles: IS_AUTHENTICATED_FULLY }
        - { path: '^/admin/', roles: ROLE_ADMIN }
        - { path: '^/.*', roles: ROLE_USER}

