# vichuploader
vich_uploader:
  db_driver: orm # or mongodb or propel or phpcr
  mappings:
    imported_file:
      uri_prefix:         /data_files
      upload_destination: '%kernel.project_dir%/public/data_files'
      namer:
        service: vich_uploader.namer_property
        options: { property: 'nameSlug'}

      inject_on_load:     false
      delete_on_update:   true
      delete_on_remove:   true
